version: '3.8'
services:
  backend:
    container_name: backend
    image: luizth/django-admin-backend:latest
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: admin_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
